### ISSUE TITLE
Request: Bigger Statistics - more options than 24h

### ISSUE THREAD

**Issue by ado464** [genielabs/HomeGenie#17]
I would love the statistics to be built up a bit, so you have a choice to show 1week 2weeks 3, and so on and not only the first 24h. The database is about 10mb so this should work? I understand it is a lot of work, but it would be a wonderful feature.

Cheers, A.

**Comment by hybridview** [comment]
I would love this feature as well. Maybe I'll take a stab at it in my spare time.

**Comment by gitbjo** [comment]
Hi,
I have also needs regarding the statistics like the above mentioned and also to be able to include data of several sensors in the same graph. Some other features like zoom and pan would make the data analysis more flexible.
I'm also ready to give a hand on that, but due to some stress in my work, I can only spend little time in the coming weeks. March should get easier. But may be we can setup some specs to start on this and Gene can help us to give directions on how it works today and where we should look at to extend it.
Regards,
gitbjo

**Comment by hybridview** [comment]
I was just thinking about pan and zoom support. For my Home Energy Monitor, I would be able to see very detailed charts (a couple of hours for example). Zoomed in, I would be able to enhance the resolution timer from every 5 minutes to every 30 seconds and see detailed spikes in usage. I just submitted a pull request that has some initial enhancements to the statistics DB queries for custom date range support and finer resolution. I was also able to learn how the statistics system functions (UI interactions/web service/database). It's a nice architecture and is very extensible.

Discussing some requirements/specs would be a great way to get everyone on the same page. My initial effort was primarily to make the statistics more configurable so I wouldn't have to recompile. Protecting the existing DB queries from SQL injection was also a good thing to nail down.

**Comment by genielabs** [comment]
@gitbjo @hybridview see what's new in r476.
Date range selection and pan and zoom support has been added.
For requests that are not strictly related to this issue topic, please open a new issue.

**Comment by genielabs** [comment]
@gitbjo 
*"Gene can help us to give directions on how it works today and where we should look at to extend it."*
Sure I would. I think a better place for this is the forum.
