### ISSUE TITLE
Need global temperature unit setting

### ISSUE THREAD

**Issue by kevin789900** [genielabs/HomeGenie#196]
HG seems to store temperature in Celsius, please add a setting that all displays of temperature will be in Fahrenheit (widgets and statistics charts).  Currently it has been reported that browser locale(?) configuration will cause HG to display F, but these settings are not accessible on mobile devices (ios/android chrome).

**Comment by JonesDK** [comment]
Hi Homegenie,
First of all thanks for a GREAT product! :)
I too wish for this feature, last week I switched to Win10 and for some reason it do not send the correct browser locate.
But, what I really miss is an "international/region" section under "Configure\maintenance". So that we can set "all" types of formates:
- Time (12H or 24H)
- Date (mm-dd-yyyy or dd-mm-yyyy)
- currency (EUR, USD, DK ect.) - Not important right now :)
- Temperature Units (C or F)

**Comment by mtanana** [comment]
Gene-  I've been monkeying around in the thermostat code.  I'm interested to hear your thoughts on this general idea.  With the thermostat code, I go back and forth.  Should we 1)  Translate everything to centigrade and let the UI decide (this is what we do now in the thermostat) or 2)  Let the format that the device sends the temperature in decide what the UI displays it in.   (This actually works for the thermostat case, because most thermostats let you set this yourself.   

I can see both being decent ways of handling the data.   

But a global setting would make it nicer for writing the code on the UI

**Comment by genielabs** [comment]
global temperature unit and date format added in r499

**Comment by kevin789900** [comment]
The new unit settings don't seem to be used in all places:
-win7/chrome: statistics doesn't use date format (it does show temperature on chart per setting)
-ios/chrome: statistics doesn't use date format or temperature setting (shows C when F is set).  Dashboard/group title bar shows C instead of F

**Comment by genielabs** [comment]
ensure to have cookies enabled
