### ISSUE TITLE
Raspbery PI GPIO Status

### ISSUE THREAD

**Issue by davidwallis3101** [genielabs/HomeGenie#297]
When input is inverted the widget displays the wrong value.

**Comment by Orkspalter** [comment]
Facing the same problem with 8 relay board connected to GPIOs

**Comment by artichost** [comment]
Try to put !OUT in Gpio settings..

**Comment by davidwallis3101** [comment]
That works but not with the widget

**Comment by gitbjo** [comment]
Hi @davidwallis3101,

this problem is due to the change in commit: [b62e6c7](https://github.com/genielabs/homegenie-packages/commit/b62e6c728b43f89e6785ff5eaef00cfcc0b56e66#diff-64f39e06a8a4d6161c5d359e1edb7150) about the Status.Level. 
As mentioned in my Pull Request #99 [comments](https://github.com/genielabs/HomeGenie/pull/99#issuecomment-70627249), it inverts the physical level only, which is the goal. 
So for example in the case of @Orkspalter, to make the relay "On" (LED on the board light is on) the GPIO output shall be 0v. So Status.Level shall remain "On" and should not be reversed.
Your change for "IN (revert)" has been removed by the same commit, but it has been documented in the description.
I would suggest to revert that commit and put on top of your commit the description for !IN. I suppose you have tested this feature.
Then we can close this issue.
