### ISSUE TITLE
Fibaro Wall plug

### ISSUE THREAD

**Issue by neslekkim** [genielabs/HomeGenie#328]
Looks like the current generation of the Wall Plug is not supported?
https://manuals.fibaro.com/wall-plug/
I got the 3.2 version now.

**Comment by Bounz** [comment]
Hi, I have this device and it works in my installation (I can control the switch and read the power consumption reports from the device).
What version of HG do you use?

**Comment by neslekkim** [comment]
It kinda works, but it comes up like an unknown device (getting an hex string), and it shows its capabilites, i thought that if the definitionfile(?) was updated for the newer version (if it have an other identification) it would show up a bit different.
Pressing the button to update pepperdb doesn't seem to do anything, is that meant to download from pepper1 or just from the github repo?

Now I can get it up as an switch or energy meter.
First I tried 1.1 beta 526, then I found out that you had forked it and intalled BE 1.1.15
Which platform is best for this app?, i'm using Windows 10 now, but planning to use an Raspberry Pi later

**Comment by Bounz** [comment]
Pepper1 DB is dead actually. So you have to manually create XML description (in pepper1 format) of the device using information from open sources and add it to lib\mig\p1db_custom.xml. Not an easy way, unfortunately.

Also, I don't recommend to use V1.1.15 right now as it has a number of problems (see details at https://homegenie.club/t/version-1-1-15-released/199). Windows is good right now because you don't have all these problems with different versions of Mono and Raspbian, but there is known issue with stuck page loads on Windows Server with IIS.
RPi is also good + it's cheap, small and power effective. I hope that after creating docker image for HG it will be much easier to run it on Raspberry.
