### ISSUE TITLE
HG 1.1-beta-526 fails to update

### ISSUE THREAD

**Issue by tuicemen** [genielabs/HomeGenie#334]
I'm running ver 1.1-beta-526 on a PI 3B+ Raspbian stretch  I wish to update to the 1.1-stable-527 version. The updater in the maintenance section shows an connection error so I wish to use the manual update but not sure which to use  the deb, tgz or exe version

**Comment by genemars** [comment]
The network update is broken on Linux due to the (returning) issue with mono TLS (and so HTTPS).
`(SecureChannelFailure (The authentication or decryption has failed.))`

Sadly there is also a bug in the `Manual Update` functionality of r526 =/, this functionality is fixed in 527 and allow to upgrade directly from a `.tgz` release file in case the automatic download fails (for example due to the above mono bug).

So at the time the only way to upgrade (from r526) is the following:

## Work-Around
- from maintenance menu -> backup configuration
- uninstall old homegenie and make a fresh install of v1.1.527
- from maintenance menu -> restore backup

If you already downloaded v1.1-stable.527 earlier today, I recommend downloading it again as I had to run multiple tests to verify/fix automatic deploy scripts.

**Comment by tuicemen** [comment]
Thanks for the heads up  I had downloaded about an hour after you posted.
I'll do a fresh install on a fresh Raspbian SD card and then do a restore.

**Comment by tuicemen** [comment]
Fresh install and restore worked flawless on a fresh Raspbian stretch.
So I attempted a HG Uninstall and fresh install of v1.1.527 on my Working SD card of 1.1.536
This didn't go as smoothly as it required several restores to get all my configured programs fully restored. The only difference with this SD image I can think of is I had HA-Bridge running on port 80 but don't see how that prevented the restore from fully taking each time.

In any case V1.1527 is now running my system.
@genemars Nice to see you back working on HG, Great program!

**Comment by genemars** [comment]
More insight about this issue:

https://tirania.org/blog/archive/2017/Nov-20.html

So, installing **mono >= 5.0.0** might solve the issue.

**Comment by tuicemen** [comment]
I've read posts about HG not working with some newer mono versions.

**Comment by tuicemen** [comment]
Awesome!
Installed this last night. I love the download available Icon on the main page opened a issue on this.
