### ISSUE TITLE
An interface for the GE Concord 4 security panel

### ISSUE THREAD

**Issue by mralapete** [genielabs/HomeGenie#347]
@genemars do you think it would be difficult for you to write an interface for HG for the above based on this GitHub project 
https://github.com/darconeous/concordd

**Comment by genemars** [comment]
Not a easy task, but possible. Though my priority now is the new HomeGenie UI and minor adaptation to HG server that are required to get best out of the new UI.

**Comment by mralapete** [comment]
Understood. As an alternative this work done in Python might make it easier to expose the panel to HG. https://github.com/JasonCarter80/concord232

This panel is is catered for in many of the Home Automation systems currently on the market.

**Comment by mralapete** [comment]
Just tested the panel automation interfaces over the last couple of weeks in Vera, Home Assistant and Home Seer. Very versatile and an ideal panel to form the centrepiece of any HA system. It's a very popular panel in the US both domestic and commercial.

**Comment by tuicemen** [comment]
@mralapete,  I have to admit I know little about this panel and only started looking at info on it after your initial post.
I don't plan on adding this or any security panel to my city HA setup. However from what I've read you can use Zwave, UPB and other protocols with this panel. So as long as you had the Concord setup to use one of those that was also supported in HG you could use the existing HG security console to display the status.
True you would have to create scripts but that isn't that difficult.
 Now if you were to do a wired setup with no wireless means of arming disarming that would be different

**Comment by tuicemen** [comment]
I've been looking into these panels since @mralapete first posted the request of support.
Not because I plan to add one or any security console to my setups but just to be informed.
from what I can gather and maybe @mralapete can confirm this is you can make several protocols interface with this Zwave and UPB to name a couple.
If true you should already be able to get the HG security panel to show Concord status info if you use Zwave.

**Comment by mralapete** [comment]
@tuicemen I have to admit I've no idea what you are talking about. Maybe you could enlighten me a little more and give me an example of what you are actually proposing. 

I've written a Python wrapper for this panel in another HA software but was hoping Gene could include a C# interface for HG. 

Are you familiar with the protocol for this panel. I had been discussing this with David Wallis on the HomeGenie.Club forum who as we know is very knowledgeable on the subject of C# and even he thinks there might be a bit of work involved here.

I have no issues running a separate server running Concordd from Darconeous and exposing it to the HG server but maybe you have a different slant on this. Maybe you could share this with us.

**Comment by mralapete** [comment]
@tuicemen not sure where you were doing your research but maybe a little look at this might give you a better idea of what I am trying to achieve via the D Bus API interfaced with HG https://github.com/darconeous/concordd

**Comment by tuicemen** [comment]
There are a couple GitHub concord projects available which use the automation module besides the one you point to. I had read a thread on cocoontech.com/forums/ where they touched on using Zwave, X10 or UPB to interface with the panel. Since I don't own one and assumed you do that you would be more up on it.  I had thought one of these could be attached to the automation module.
I don't plan on doing anything with one of these so digging into the protocol isn't something I'm looking to do at this time but  you and or @genemars may find these worth looking at 
https://github.com/csdozier/device-concord4
or https://github.com/douglasdecouto/py-concord
Obviously I don't have this panel and anyone wishing to create an addon interface for HG would require one, and the automation module.

**Comment by mralapete** [comment]
@tuicemen I've been working on this panel for over 20 years. I've programmed the eeproms. I'm extremely familiar with the protocol. In fact I've converted them for use in the European market so I'm fairly familiar with all the working projects out there but thanks for pointing out these links anyway.

I strongly advise obtaining this panel or something similar to experience the true feeling of a professional security system.

**Comment by tuicemen** [comment]
Thanks but If I ever need a professional grade security system I'll look for something much newer and certainly not a DIY project. Not that there is anything wrong with a DIY security project I'd just want something more plug and play if I were to go the professional grade security system. Right now my dog makes my feel safer then any security system.

**Comment by mralapete** [comment]
As I said @tuicemen the last word. Good luck with that off grid X10 security premises you have protected. Hope you dog barks loud enough.

Maybe when you have something written you can call your own you could share it here or over on your X10 Forum.
