### ISSUE TITLE
Updating Issue

### ISSUE THREAD

**Issue by alzzy** [genielabs/HomeGenie#354]
HG on Pi Zero with stable.29 and stable.30

I noticed on my last two updates stable.29 and .30 the update window with the spinning wheel never says complete, just keeps spinning saying "installing files- HG service stopped" even after 15 minutes. How long should it take? I can see the HG home screen in the background responding to the built in macros during the process.

**Comment by tuicemen** [comment]
Since  I've always experienced this when updating using my smartphone I never considered this an issue with HG but my phone.
 I figured the browser just was failing to refresh and a manual refresh always brought up the new build.
I believe I still have one HG pi I've not updated so I'll use my windows PC and browser for it and report back. I know older updates using my windows browser never hung.

**Comment by mralapete** [comment]
Run HG in debug mode, copy and paste the results here on the GitHub.

**Comment by genemars** [comment]
Fixed by **v1.2-stable.31**.
