### ISSUE TITLE
Once again a new release without release notes

### ISSUE THREAD

**Issue by mralapete** [genielabs/HomeGenie#369]
It really would help users if you posted release notes advising what changes are being made and what if any of these changes would be termed as breaking changes. You seemed to have dispensed with this practice a while back.

I just noticed someone posting a breaking change with IP cameras but the post was closed for some reason without any reason why this happened

Might be worth looking at Home Assistant to see how they handle their update protocols.

**Comment by genemars** [comment]
@mralapete if you see the commit logs you'll notice that everything IS commented. 
The whole build process has been automated but yet the description of the release has not been automated.
I just manually edited the release description with things changed, maybe this made you happy now.
I strongly encourage you to switch to any other software especially because they don't have PASSIVE users but they have a tons of REAL contributors that help with coding and that here, as you can see, are missing =)
There is no folk interested in HomeGenie. I only see you complaining all the time and @tuiceman reporting issues.
I may accept your continous criticizing against HG, but since (unfortunately) I am the only developer here, you're continuously and directly attacking me and my work without being of any help and most of times being just rude without any reason.
So I wonder why on earth are you still here? =)

**Comment by tuicemen** [comment]
I find very few users actually bother to post issues or suggestions here on GitHub for any software :( .
Instead they turn to forums for help. 
Myself, having coded and publicly releasing free software as @genemars  does, I know all releases don't require a release description each and every time. Most times I updated my programs were from bugs or issues no one reported and only I noticed.
I for one am thrilled to see HG actively being improved and sometimes will grab a build as soon as it is posted.
Release info stating what was changed is nice but If anyone truly wishes to know what was changed looking at the code usually (but not always) will reveal that.
I've only been using HG for a short time but it has stood the test of time which very few HA programs do. 
Suggesting a developer follow the same routine as another software is insulting though I'm sure that wasn't @mralapete intent.
I've been accused of demanding things when posting suggestions and or issues which was never my intent as well, that is the problem with the written word, every reader can read into a post differently. 

@genemars, Keep up the Good work! There are more of us using HG then you may realize.

PS. The Generic Camera issue was noticed only on one machine and since it also mentioned HG states a warning of backing up prior to updating I felt there was no reason to keep it open.

**Comment by mralapete** [comment]
@genemars the reason why you are the only developer on this project is that you walked away from the project two years ago stating that HG was a completed project and closed down the original HG forum.

Many users and experienced coders made numerous useful contributions to your project, some which are still in daily use. These people offered on many occasions to take over the running of that forum for you and even offered their development services too. You chose not to reply to these offers and as a result your project was forked by Alex and a new community was established.

From nowhere you decided to revive your development of HG knowing that a forked version was available causing further confusion and of course disregarding all the efforts that were made in your absence. How can anyone seriously be expected to contribute on a community basis on the GitHub

It was suggested by many at the time that HG was far from a finished project. Clearly you understand that now. 

Your project is only as good as the people you develop it for and those who use it. You had a wonderful experienced user base at one stage which has all but disappeared as can be seen from the current input.

Not to worry. As you have suggested I too have moved on so won’t be bothering you any further with suggestions or ideas.

**Comment by noliono** [comment]
> There is no folk interested in HomeGenie. I only see you complaining all the time and @tuiceman reporting issues.

I spend some times some years ago (start in 2013) with the HomeGenie in beta version. Now HomeGenie is working fine : 
- with all my devices 
- No bug and no need to reboot
- No SD/MicroSD crash (Other system like jeedom crash SD/MicroSD probably due to too much write on it)
- Can be customize easily with program/script

But i didn't say that there is no need to enhanced. But today, my system (HG and My Program) is running and i nearly forgot it in a corner of my office :)
I have just updated HG recently to test my wemo program enhanced by you @genemars.
Anyway, Thank you very much @genemars for HG ! 

I think your idea to separate : 
- HG
- HG Program

was a good ! Because on my side, I thought naively that i could help code HG but that was not my skill probably. But I write some HG Program. 

@genemars Why did you don't work on HG with @Bounz which seems to well known code and HG code ?

On my side, I am trying to speak about HG to some automation French WebSite.

**Comment by bkenobi** [comment]
I looked at the HG code years ago when I got started.  I'm not a C# programmer by education and it took a fair bit of effort to learn enough to build the apps I did.  I personally would have been a detractor if I attempted to fork anything though I considered a couple modifications to the X10 system.  Instead, I worked on things I felt capable of finishing.  They were solid enough that I released them on GitHub for others should they see them as useful too.

As for the project as a whole, I think people felt somewhat abandoned when the forum was closed and the project was marked as complete even when left in beta.  There have been many projects I have seen this happen to and they basically die off.  In the case of HG, a portion of the user base that was dedicated to it moved to the HG.club forum.  Unfortunately (IMO), the development of that fork seemed primarily based on Windows improvements rather than the functionality of the system HA related.  Since I'm RPi based, that fork caused me more issues than it solved.  The forum is also rather clunky resulting in a poor user experience compared to classic forum software.  So, I went from being heavily involved in testing new releases and writing apps to other projects.  I can't speak for others, but I saw a few posts from original users moving on due to no help for issues they were having.

I understand that you have some personal reasons for the decision and since it's your project and your the only coder it's your choice alone.  I would just point out that if the forum had remained open, the community might have stuck together and not abandoned the project.  All the momentum that had been built by your great work essentially stalled when there was no location for users to get a question answered by either the author or other experienced users.  I still have my original RPi running HG 525 and it's very stable.  It's not perfect as it requires a reboot every couple months.  It's also based on Mono and the email notification is not robust due to certificates.  Overall though, HG is very solid and one of the better options for HA IMO.
