### ISSUE TITLE
add a clock widget

### ISSUE THREAD

**Issue by Nosreme1** [genielabs/HomeGenie#372]
First, I thank the entire team for this wonderful project.
I wanted to know how I could add a clock widget in a dashboard please.
Is it possible to do that?
Thank you for your answers.

**Comment by tuicemen** [comment]
It is totally Doable there is even a widget for it that was created by one of HG users @jshan.
I don't believe it made it into the HG Package manager but you can get it from the old HG (read only)forum: http://old.homegenie.club:8080/www.homegenie.it/forum/index27c5.html?topic=1024.msg6255#msg6255

**Comment by Nosreme1** [comment]
@tuicemen thank for your answer. I downloaded " 1006-ShowDateTime.hgx" file, how could I upload it into Homegenie and use it in my dashboards?
Thanks

**Comment by tuicemen** [comment]
@Nosreme1 from HG "configure/programs/device and things" click on the actions tab (bottom right) click import program then browse to your downloaded  1006-ShowDateTime.hgx file and import.
Since I don't use this I'm not sure if this is the group that it is meant for so if it doesn't appear after the import you may have to search the other groups for it. when you find it, it will need to be enabled so you can use it in the HG interface.

**Comment by Nosreme1** [comment]
It works
Thanks

**Comment by tuicemen** [comment]
@Nosreme1  Glad to see you have it working . maybe you can close your issue? =)
