### ISSUE TITLE
OpenWeather in Metric only Except Temp

### ISSUE THREAD

**Issue by LostDog88** [genielabs/HomeGenie#376]
### Expected behavior
Report wind in Imperial measurement not metric.

### Actual behavior
Unable to change setting. 

### Steps to reproduce the problem starting from a fresh install

  1. 
  2.
  3.

### Specifications

  - Version: 1.1-stable.527
  - Operating System: 
  - .Net/Mono runtime version:
  - Hardware configuration:

**Comment by tuicemen** [comment]
@LostDog88  I've been looking at what OpenWeatherMap is being asked for by HG. and what can be asked for.
@genemars currently has metric measurements hard coded in though it is possible to retrieve the actual values in imperial or metric measures.
 I doubt your open to playing with the Openweather code as any customization to it would be lost on a Update without reinstalling a backup after each update.
However viewing the API call options here https://openweathermap.org/current you can figure out what to change in the code yourself just make a backup prior to playing.

**Comment by tuicemen** [comment]
I decided to play with switching the values to imperial and was able to get the values to display correct Temperature shows in the top bar on the group page but the widget  still doesn't display the  &#8457; This can be fix by switching the  Unicodes `&#8451;`  in the Widget Java section with `&#8457;`
Now the unfortunate part for **me** is HG still sees the  &#8457; value and not the &#8451; values.
I can fix this in the widget but have not dug into the HG code to see what the issue is with the value reported in the UI (top right corner).
Hopefully the next update will address this.

**Comment by tuicemen** [comment]
@LostDog88  I believe I have all metric/imperial displays worked out.
Fixes are outlined in #382 perhaps you can test them out and if they work for you this issue can be closed.
I've also put in a pull request so enhancements can be added to the next HG build once reviewed #388
