### ISSUE TITLE
email information will not update

### ISSUE THREAD

**Issue by yorlik-too** [genielabs/HomeGenie#384]
### Expected behavior
change email PID 142 info and it go into effect

### Actual behavior
change email PID 142 info and it does NOT go into effect

### Steps to reproduce the problem starting from a fresh install
  1. update HG to major new update
  2. try to send an email - that used to go just find with present settings
  3. no send;  crashes same as I reported in previous bug report

### Specifications

  - Version: latest
  - Operating System: rasp pi latest
  - .Net/Mono runtime version: latest, same as last reported
  - Hardware configuration:  pi

#### Additional configuration notes
Last time this happened Ihad to make a new image with NO email info so I could enter it FRESH - and it took and worked.... Until this latest set of major updates.  Now no amount of changing any info makes it 'take.'

I am left with ZERO email capability again.

**Comment by yorlik-too** [comment]
I asked last time I reported this but received no reply.  Asking again as it really would be  nice to have HG email capability back:  Where is the email data for PID 142 actually stored?  Can I go delete it or change it there?

**Comment by tuicemen** [comment]
@genemars I also had this issue with one of my RPi. 
I know  @yorlik-too has extensive emailings triggered and the Pi that got messed up for me was handling some emailings the other wasn't however it was configured with an email address settings.
So I'm wondering that maybe during updates if HG is triggered to send an e-mail that it is messing something up.  If the bug that is causing this can't be rooted out maybe HG can disable the email program prior to updating.
Users can do this themselves but I know I'll forget to do that at least once or twice.

**Comment by genemars** [comment]
@yorlik-too do you use SMTP authentication? I just found a bug that occurs when NOT using authentication. Also another issue is that previous settings are retained until you restart the program that is sending the e-mail.

**Comment by yorlik-too** [comment]
Thanks for finding SOMETHING!  I wish I could help more!

Unfortunately gmail DOES use SSL and authentication, so what you found may not help me.  For reference, I tried again just now and it again failed to send.  I had just made a new SD image so obviously rebooted.  No difference, still fails.  On latest HG file.

here is link to log file showing the failure:

https://www.dropbox.com/s/zc3cir051c1ky7x/homegenie_log_bad-email.csv?dl=0

Does this help solve the issue?

Thank you.

**Comment by genemars** [comment]
@yorlik-too if you are using `465` as SSL port, can you try with `587`?

**Comment by tuicemen** [comment]
@genemars  the ssl port is not the issue in this case nor was the email bug you found. 
Nor is the email server at fault as I use Hotmail  @yorlik-too uses g-mail.
I too have seen this on one of my Pis which I've not attempted to fix yet. 
I was using SSL port 587 .
I still believe the issue that caused this was HG attempting to send email while in the process of doing an update. this changed something in the code which possibly adds an extra character messing with the settings.
All email connection settings info remains in HG and is the same prior to the update however sending fails .
@yorlik-too is trying to find where in the HG code email sending is handled in order to dig into the issue as to why the sending is failing now . If I remember what ever got changed it doesn't allow new email settings the user tries to add (change) to take affect.

**Comment by yorlik-too** [comment]
Thanks guys.
Gene, I changed to port 587;  failed to send
I then restarted HG service in config->maint page, tried again;  WORKED!  SENT!!!

I did NOT update to ver1.3-stable.4 yet
I will do that tonight and verify it still works!

THANK YOU SO MUCH FOR FIXING THE ISSUE!!
