### ISSUE TITLE
GPIO not working with RP1 4

### ISSUE THREAD

**Issue by guytpetj** [genielabs/HomeGenie#400]
Using RPi 4 the GPIO does not work in Home Genie. GPIO works from command line and with python.

Same configuration, back-up file, restored on Rpi 3 works great, so problem is RPI 4 / Buster related.

**Comment by mralapete** [comment]
Have you tried installing HG on Raspbian Stretch using your Pi4. You are aware very little development work has been done on HG in over a year and certainly none since the release of Pi4 or Buster. Changes on how GPIO pull ups are handled on the Pi 4 as far as I know have not been accounted for in HG.
