### ISSUE TITLE
More compact Controls UI (or custom skins)

### ISSUE THREAD

**Issue by Ziflin** [genielabs/HomeGenie#41]
Is it possible to have an option for a more compact control UI.  Currently only 2 devices fit on the screen of my Note 2 when using the Web UI.  The "ZWave 3" line could be replaced with the time and the padding around the switch reduced considerably to allow a few more devices to display.  The status display at the bottom could probably just be the icon placed to the left of the device's name.  

Perhaps just a way to assign a custom skin to use would be enough so that I would not have to modify the main skin locally that I assumed would be overwritten when performing an update?

**Comment by genielabs** [comment]
homegenie has now got built-in widget editor, so you can edit widgets and change them as you like.

**Comment by Ziflin** [comment]
Awesome!  I'll check it out.  Still very happy with our daily use of HG!

**Comment by tarasaint** [comment]
Hi. I've created a modified set of widgets for myself that might be interesting to anyone that got here to this thread / issue. I'll attach images from my phone and computer. If anyone is interested, tell me and I'll upload the files I've modified.

It's not a full set of widgets, for now. Lights, Switches and Dimmers are implemented, since that is what I most want to control from my phone. I have a Homegenie icon on my iPhone home screen that takes me straight to what you see attached.

The icon on the left clicks to the controlpopup (e.g. dimmer knob), and the name clicks to the configuration/edit popup. I figure if I really want to know what z-wave node it is, I can touch the name, but for pure control functionality, that is lost space.
![img_3553](https://cloud.githubusercontent.com/assets/9024383/6561516/3132ce66-c692-11e4-809b-8ae29d0052d9.PNG)
![img_3554](https://cloud.githubusercontent.com/assets/9024383/6561520/39352596-c692-11e4-82ee-b031d472fed5.PNG)
![screenshot 2015-03-09 19 27 54](https://cloud.githubusercontent.com/assets/9024383/6561581/89d78b06-c692-11e4-9ed9-0a27edac6568.png)

**Comment by tarasaint** [comment]
By the by, I didn't change the popups at all. The dimmer knob, for example, is most comfortable if it's nice and big on the phone. A reasonably usable range slider on the widgets would leave no room for the name, imo.

**Comment by genielabs** [comment]
@tarasaint 
very nice, please export them using widgets editor functionality and share in the forum.
http://www.homegenie.it/forum

**Comment by tarasaint** [comment]
Awaiting forum approval. Different email, but recognizable.

This might be important before posting them. I made the changes as modifications to the homegenie/generic widgets. That saved me figuring out how to make the widgets bindable to the modules from the config drop-down.

Do you prefer me to ask on the forum devel area how to add them and make them available in from the drop-down, instead of replacing the default widgets. It seems like a poor solution to be substituting yours, especially since I have also made a few non-cosmetic changes to the code. In particular, I have included Sensor.Power reports from Fibaro wall plugs in the watts displayed, both widget specific and group indicator.

**Comment by genielabs** [comment]
@tarasaint I think that something like a widget dropdown list is what could be added to hg module options popup to let user force a specific widget for a module. file a issue (enhancement)
