### ISSUE TITLE
Recent updates to HomeGenie Library files

### ISSUE THREAD

**Issue by soxfan1966** [genielabs/HomeGenie#448]
Good morning,

I have noticed you recently updated packages of various source code etc but the overall HomeGenie release is still at version v1.3-stable.19, which I have been running for some time now.

In the readme file for running HG, there is this info:
Running
netcore

cd src/HomeGenie/bin/Debug/netcore3.1
./HomeGenie # (or 'dotnet HomeGenie.dll')
net461

cd src/HomeGenie.Net461/bin/Debug
./HomeGenie.exe # (or 'mono HomeGene.exe')

The service I am running in my raspberry pi is using this:
/usr/bin/mono /home/pi/homegenie/HomeGenie.exe --log

I think that means I am running the net461 version, which I believe is the old/existing/current version, but I am not sure.

Is it possible with the HG release I have to run the netcore version?  Would some of the packages need to be updated on my end to reflect the changes / updates you have made recently?   Is there advantage to running the netcore version over the net461 version ?

Thanks

**Comment by mralapete** [comment]
You can see from the release history that anything beyond v19 stable is in Alpha state and there’s been no further development on this for over one year. If you did get any recent update notification I imagine it was an automated one in relation to the Nuget package manager. https://github.com/genielabs/HomeGenie/releases

If you want stability stay as you are. If you fancy a challenge with an Alpha go ahead and upgrade. If you do you will probably be on your own. The HG forum is down and there won’t be too many opportunities to ask questions and receive replies.

**Comment by mralapete** [comment]
Do bear in mind the majority if not all your Alpha testers come from an X10 Windows based background. You mentioned in your readme notes that manual changes need to be made to facilitate the use of X10 as HG no longer runs as root and obviously will not have automatic access to the USB ports. You do include instructions for achieving this In Ubuntu and while the RPI4 does run Ubuntu the RPI3+ or lower does not. Have you personally installed/tested the Alpha on the RPI platform yet.

**Comment by genemars** [comment]
>  You mentioned in your readme notes that manual changes need to be made to facilitate the use of X10 as HG no longer runs as root 

@mralapete no manual changes are needed anymore. The installation script takes care of fixing the required permissions to access either GPIO/SPI/I2C and USB ports.
This is achieved by adding the `homegenie` user to the system groups `dialout` and `gpio`.
https://github.com/genielabs/HomeGenie/blob/master/assets/deploy/linux/DEBIAN/postinst#L9

> Have you personally installed/tested the Alpha on the RPI platform yet.

Yes, I already tried new HG on a RaspberryPi and it was running nicely with netcore3.1 (donet) and also played with GPIO and IoT SDK.
I haven't tried after upgrading HG to `net6`, but I suppose it can just be better.

>  I imagine it was an automated one in relation to the Nuget package manager. https://github.com/genielabs/HomeGenie/releases from dependabot

please do not guess things that are actually not true =)  you can already browse the new code that I have been updating regularly in the last month.

>  there won’t be too many opportunities to ask questions and receive replies.

that's not true. I reply to questions filed via `Issues` here whenever I get a chance to.

**Comment by mralapete** [comment]
It’s the “whenever I get a chance” part that puzzles me. As I mentioned previously up to now it was over one and a half years since the last Alpha release and then silence. I think most had given up seeing any further progress on this particular round of development. There was another forum setup by a very knowledgeable user of HG but that’s now gone too and honestly the GitHub is hardly the place to discuss user problems. We’ve had this discussion before so there’s no point repeating it again here. Suffice to say that many of your knowledgeable contributors to the original project are no longer contributing here. These are not criticisms these are facts. Maybe you can take this on board going forward.

**Comment by genemars** [comment]
My father died a year and two months ago. You know, things happen to people in life and you are being very numb and rude.
It's good that old HG users have found something better somewhere else than what they ultimately get here.
I would suggest you do the same instead of trolling here.

**Comment by soxfan1966** [comment]
Gene,
Sorry to hear about the loss of your dad.  My mom passed away 2 years ago.  Losing a family member is difficult and everyone deals with it in their own way and time.

I for one am grateful for your efforts with HG and updating and I am sure there may be a few others as well.  So please keep me posted on your progress.

Thank you

**Comment by mralapete** [comment]
> My father died a year and two months ago. You know, things happen to people in life and you are being very numb and rude.
> It's good that old HG users have found something better somewhere else than what they ultimately get here.
> I would suggest you do the same instead of trolling here.

I truly am sorry to hear of your loss. Many of us have indeed suffered similar losses over the years so I’ve no doubt we know what you are experiencing.

You’ll forgive me for my comments above based on previous experiences with this project. The start/stop nature of development followed by a complete stop in 2017 with the statement that HG was then a finished project followed by the take down of the original forum and the refusal to allow anyone to continue maintaining that forum after numerous offers to do so. You can see why I might be a little suspicious.

That forum was a valuable source of reference for many users and included many valuable contributions from some very skilled coders who you ended up chasing away. That’s not including the users who spent countless hours acting as Alpha and Beta testers for your project.

it was a little disingenuous of you to respond to my comments without giving a little background or context as to why I may have made them. 

Yes you now have some recent converts to HG but maybe you could acknowledge the efforts others put in over the intervening years (I do not include myself in that list). Hopefully they will contribute in a meaningful way to help you get where you need to go.

Honestly Gene….trolling. I’m way too busy for all that. I just stick with the facts that others may not be aware of. 

Take care and I really do hope you can  attract a more experienced and eclectic  user base now that you are back developing for the moment.

**Comment by genemars** [comment]
@mralapete do you think I ever raised a single penny from this project? I only have expenses. Do you think I am a rich person that doesn't need to work for a living and can just play with HG all the time? Have you ever seen many active code contributors around this code (huge code)? Have you ever seen how many contributors are around other well known mainstream projects?
Do you think I have to tell you and others what I am going through in my life at all?
Do you know what open source is at all?
It's about 10 years of work I spent on HG and other related projects and I never complained about too few users around this project. Because my effort is sincere and I truly believe in what I am doing despite you like it or not I will continue doing it.
Your reply didn't help at all, you just made your point worse. You just made my day worse.
You were not helpful at all. Maybe you don't realize that.
