### ISSUE TITLE
What is the overarching strategy/plan for HG 1.4+ vs. HG 1.3?

### ISSUE THREAD

**Issue by EnGamma** [genielabs/HomeGenie#456]
I've looked around for a doc that explains the overall thinking behind 1.4+ vs. 1.3, including a comparison of features and progress in implementing them, but have not found it.   Here are some of my questions:

1.  What was the reason for the 1.4 rewrites? [for me the attraction is Raspberry Pi install packages that don't require mono which caused me much trouble]
2.  There are significant features that were in 1.3 but are not (yet?) in 1.4 betas.   Is this because 1.4 is a work in progress or are the missing features being abandoned?   To address this, I would recommend publishing a table showing which features in 1.3 are available in the current 1.4 beta and which are not.  Also, have the table show for missing features whether or not are they planned for implementation?
3.  The v1.3 docs don't answer all the needed questions because of 1.4 vs. 1.3 differences.   Can you augment, even if in a temporary way, with additional instructions to address key 1.4 differences.

Thanks for all the hard work on a great program.   I'm just a little confused right now about the direction you are headed in.

**Comment by tuicemen** [comment]
I believe many users are as puzzled as you.
During the early stages of the Alfa builds @genemars has a discussion section setup so users could ask questions and submit suggestions this helped many understand how HG was moving. The ability to move between the old UI and new will make it extremely difficult for new and old users without an extensive writen help document.
Currently HG appears to be moving backwards to me as the wiget editor is gone and we informed during alpha testing it would not return. This makes many end user programs either unusable or extremely limited in their functionality. I hope @genemars reconsiders the elimination of the wiget editor and allows custom widgets again.  For me I need the ability to view ip cameras and we've lost that as well since alpha 7 I believe ( not sure why).

**Comment by hs6666** [comment]
personally speaking due to the lack of communication ... i am strictly only testing this on a seperate isolated vlan with logging of outward connections to the web

**Comment by EnGamma** [comment]
Yes, very disappointing.  Noncommutative behavior is very odd.

**Comment by genemars** [comment]
Have you read this?

https://github.com/genielabs/HomeGenie/blob/master/CONTRIBUTING.md

and maybe this?

https://developer.mozilla.org/en-US/docs/MDN/Community/Open_source_etiquette

**Comment by EnGamma** [comment]
> Have you read this?
> 
> https://github.com/genielabs/HomeGenie/blob/master/CONTRIBUTING.md
> 
> and maybe this?
> 
> https://developer.mozilla.org/en-US/docs/MDN/Community/Open_source_etiquette

I think if you go back to my original post, you will see that it was entirely consistent with these conduct guides you linked.   I spent hours going through the available documentation looking for answers to my questions but could not find them.   I would have been happy to be pointed to somewhere where there were some answers to questions that I think are pretty reasonable considering the magnitude of changes being made to HG.   I am interested in contributing, but I have been struggling to just keep HG 1.4 functioning through the beta releases, including loss and reconstruction of settings etc.--all of which may be worth it with some view of the end in mind.

But there was no response from you at all other than to close the topic, without a word.  That's pretty much the definition of non-communicative and yes I'm disappointed.
